### PR TITLE
build: use whiskers

### PR DESCRIPTION
**Pull request by uncenter**
Adds [Whiskers](https://github.com/catppuccin/toolbox/tree/main/whiskers), Catppuccin's internal templating tool, to build the themes. Instead of editing the `.css` files directly, edit the `youtubemusic.tera` file and then run `just build` to build the output themes. You will need Whiskers (linked above) and *optionally* [Just](https://github.com/casey/just) installed.

~~Draft until https://github.com/catppuccin/toolbox/pull/217 is (hopefully) merged so that the core CSS can be in a separate file from the Whiskers template (easier to edit I think).~~ Actually I don't really think this is helpful (light/dark style configuration can only be done in the Tera template so)...

### CODE REVIEW

**Comment by kerichdev** [comment]
a bit late but checking in here - is this still needed? also why are the few styles under the fork changes in latte deleted? im pretty sure there were issues with them - hence why they're there

**Comment by uncenter** [comment]
> is this still needed?

As opposed to... what exactly?

> why are the few styles under the fork changes in latte deleted?

Not documented/commented at all, couldn't be sure if it was intentional or a vestige of the past.

**Comment by uncenter** [comment]
Also, looking at the diff in this PR... is it realy not using any of the colors between surface0 and subtext1?!

**Comment by kerichdev** [comment]
ill look at the variations albeit im not exactly certain if they're needed - youtube music itself is mostly done in black, so i stuck with the uniform look.

ill familiarize myself with the tool for a moment and merge afterwards.

**Comment by uncenter** [comment]
In our YouTube port we use them frequently, FYI.

**Review by kerichdev — APPROVED** [review]
lgtm, lets try this out

**Pull request merged**
