### PR TITLE
Mocha change

### PR DESCRIPTION
**Pull request by ofsho**
# Mocha
## Before
image
image
## After
image
image
(the second one needs some work)

The rest will come with future commits (its like 1 second)

### CODE REVIEW

**Comment by ofsho** [comment]
I have some problems with latte so the update will be later on

**Comment by rubyowo** [comment]
Thanks for the PR! :)
Can we have the red text + icons in the first image changed to catppuccin red? thanks again

Closes #3 btw

**Comment by ofsho** [comment]
btw the centered text isn't present anymore

**Comment by ofsho** [comment]
ok sure :)

**Comment by ofsho** [comment]
nvm, its impossible

**Comment by ofsho** [comment]
I will do the images later

**Comment by ofsho** [comment]
I'll do it tomorrow

**Comment by kerichdev** [comment]
Fixed in 29da571

**Pull request closed without merging**
